// frontend/src/app/components/Login.tsx
import { useState } from 'react';
import { ShieldCheck, Package, UserPlus } from 'lucide-react';

interface LoginProps {
  onLogin: (role: string, username: string) => void;
}

export function Login({ onLogin }: LoginProps) {
  const [isLogin, setIsLogin] = useState(true);
  const [username, setUsername] = useState('');
  const [password, setPassword] = useState('');
  const [confirmPassword, setConfirmPassword] = useState('');
  const [email, setEmail] = useState('');
  const [selectedRole, setSelectedRole] = useState('rescue');

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    
    if (isLogin) {
      // 登录逻辑
      if (username && password) {
        onLogin(selectedRole, username);
      }
    } else {
      // 注册逻辑
      if (username && password && confirmPassword && email) {
        if (password !== confirmPassword) {
          alert('两次输入的密码不一致');
          return;
        }
        // 注册成功后自动登录
        alert('注册成功！');
        onLogin(selectedRole, username);
      }
    }
  };

  const roles = [
    { value: 'admin', label: '系统管理员', desc: '拥有全部系统权限' },
    { value: 'warehouse', label: '仓库管理员', desc: '管理物资库存' },
    { value: 'rescue', label: '救援人员', desc: '申请和接收物资' }
  ];

  return (
    <div className="min-h-screen bg-gradient-to-br from-blue-50 to-slate-100 flex items-center justify-center p-4">
      <div className="w-full max-w-md">
        {/* Logo and Title */}
        <div className="text-center mb-8">
          <div className="inline-flex items-center justify-center w-16 h-16 bg-blue-600 rounded-2xl mb-4">
            <Package className="w-8 h-8 text-white" />
          </div>
          <h1 className="text-3xl font-bold text-slate-800 mb-2">救援物资管理系统</h1>
          <p className="text-slate-500">Emergency Relief Material Management System</p>
        </div>

        {/* Login/Register Card */}
        <div className="bg-white rounded-2xl shadow-lg p-8">
          {/* Toggle Tabs */}
          <div className="flex gap-2 mb-6 p-1 bg-slate-100 rounded-lg">
            <button
              type="button"
              onClick={() => setIsLogin(true)}
              className={`flex-1 py-2 rounded-lg font-medium transition-all ${
                isLogin
                  ? 'bg-white text-blue-600 shadow-sm'
                  : 'text-slate-600 hover:text-slate-800'
              }`}
            >
              登录
            </button>
            <button
              type="button"
              onClick={() => setIsLogin(false)}
              className={`flex-1 py-2 rounded-lg font-medium transition-all ${
                !isLogin
                  ? 'bg-white text-blue-600 shadow-sm'
                  : 'text-slate-600 hover:text-slate-800'
              }`}
            >
              注册
            </button>
          </div>

          <form onSubmit={handleSubmit} className="space-y-6">
            {/* Username */}
            <div>
              <label className="block text-sm font-medium text-slate-700 mb-2">
                用户名
              </label>
              <input
                type="text"
                value={username}
                onChange={(e) => setUsername(e.target.value)}
                className="w-full px-4 py-3 border border-slate-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-transparent"
                placeholder="请输入用户名"
                required
              />
            </div>

            {/* Email (仅注册时显示) */}
            {!isLogin && (
              <div>
                <label className="block text-sm font-medium text-slate-700 mb-2">
                  邮箱
                </label>
                <input
                  type="email"
                  value={email}
                  onChange={(e) => setEmail(e.target.value)}
                  className="w-full px-4 py-3 border border-slate-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-transparent"
                  placeholder="请输入邮箱"
                  required
                />
              </div>
            )}

            {/* Password */}
            <div>
              <label className="block text-sm font-medium text-slate-700 mb-2">
                密码
              </label>
              <input
                type="password"
                value={password}
                onChange={(e) => setPassword(e.target.value)}
                className="w-full px-4 py-3 border border-slate-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-transparent"
                placeholder="请输入密码"
                required
              />
            </div>

            {/* Confirm Password (仅注册时显示) */}
            {!isLogin && (
              <div>
                <label className="block text-sm font-medium text-slate-700 mb-2">
                  确认密码
                </label>
                <input
                  type="password"
                  value={confirmPassword}
                  onChange={(e) => setConfirmPassword(e.target.value)}
                  className="w-full px-4 py-3 border border-slate-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-transparent"
                  placeholder="请再次输入密码"
                  required
                />
              </div>
            )}

            {/* Role Selection */}
            <div>
              <label className="block text-sm font-medium text-slate-700 mb-3">
                {isLogin ? '登录角色' : '注册角色'}
              </label>
              <div className="grid gap-3">
                {roles.map((role) => (
                  <label
                    key={role.value}
                    className={`flex items-start p-4 border-2 rounded-lg cursor-pointer transition-all ${
                      selectedRole === role.value
                        ? 'border-blue-500 bg-blue-50'
                        : 'border-slate-200 hover:border-blue-300'
                    }`}
                  >
                    <input
                      type="radio"
                      name="role"
                      value={role.value}
                      checked={selectedRole === role.value}
                      onChange={(e) => setSelectedRole(e.target.value)}
                      className="mt-1 w-4 h-4 text-blue-600"
                    />
                    <div className="ml-3 flex-1">
                      <div className="font-medium text-slate-800">{role.label}</div>
                      <div className="text-sm text-slate-500">{role.desc}</div>
                    </div>
                  </label>
                ))}
              </div>
            </div>

            {/* Submit Button */}
            <button
              type="submit"
              className="w-full bg-blue-600 text-white py-3 rounded-lg hover:bg-blue-700 transition-colors flex items-center justify-center gap-2 font-medium"
            >
              {isLogin ? (
                <>
                  <ShieldCheck className="w-5 h-5" />
                  安全登录
                </>
              ) : (
                <>
                  <UserPlus className="w-5 h-5" />
                  立即注册
                </>
              )}
            </button>
          </form>

          {/* Footer Info */}
          <div className="mt-6 pt-6 border-t border-slate-200">
            <p className="text-center text-sm text-slate-500">
              基于 Golang 构建 · JWT 安全认证
            </p>
          </div>
        </div>

        {/* Demo Hint */}
        <div className="mt-6 text-center text-sm text-slate-600 bg-white/60 backdrop-blur-sm rounded-lg p-4">
          <p>演示提示：输入任意信息即可{isLogin ? '登录' : '注册'}</p>
        </div>
      </div>
    </div>
  );
}

// frontend/app/src/views/Login.vue
<script setup lang="ts">
import { ref } from 'vue'
import { useRouter } from 'vue-router'
import { useUserStore } from '@/stores/user'

const username = ref('')
const password = ref('')
const role = ref('admin')
const isLoading = ref(false)
const userStore = useUserStore()
const router = useRouter()

const handleLogin = async () => {
    isLoading.value = true
    try {
        const success = await userStore.login({ username: username.value, password: password.value }, role.value)
        if (success) {
            router.push('/dashboard')
        }
    } catch (error) {
        console.error('Login failed', error)
    } finally {
        isLoading.value = false
    }
}
</script>

<template>
  <div class="h-screen w-full flex items-center justify-center bg-gray-900 overflow-hidden relative">
      <!-- Background Effect -->
      <div class="absolute inset-0 bg-gradient-to-br from-gray-900 via-gray-800 to-black z-0"></div>
      <div class="absolute top-0 left-0 w-full h-full opacity-10 pointer-events-none" style="background-image: url('https://grainy-gradients.vercel.app/noise.svg');"></div>

      <div class="z-10 bg-white/10 backdrop-blur-lg border border-white/20 p-8 rounded-2xl shadow-2xl w-full max-w-md transform transition-all hover:scale-[1.01]">
          <h2 class="text-3xl font-bold text-white mb-2 text-center tracking-tight">系统访问</h2>
          <p class="text-gray-400 text-center mb-8 text-sm">应急物资调度指挥中心</p>

          <form @submit.prevent="handleLogin" class="space-y-6">
              <div>
                  <label class="block text-sm font-medium text-gray-300 mb-1">用户名</label>
                  <input v-model="username" type="text" class="w-full bg-gray-800/50 border border-gray-600 rounded-lg px-4 py-3 text-white focus:outline-none focus:ring-2 focus:ring-emerald-500 transition-all placeholder-gray-500" placeholder="请输入用户名" required />
              </div>

               <div>
                  <label class="block text-sm font-medium text-gray-300 mb-1">密码</label>
                  <input v-model="password" type="password" class="w-full bg-gray-800/50 border border-gray-600 rounded-lg px-4 py-3 text-white focus:outline-none focus:ring-2 focus:ring-emerald-500 transition-all placeholder-gray-500" placeholder="••••••••" required />
              </div>

              <div>
                  <label class="block text-sm font-medium text-gray-300 mb-1">角色模拟</label>
                  <select v-model="role" class="w-full bg-gray-800/50 border border-gray-600 rounded-lg px-4 py-3 text-white focus:outline-none focus:ring-2 focus:ring-emerald-500 transition-all">
                      <option value="admin">系统管理员</option>
                      <option value="warehouse">仓库管理员</option>
                      <option value="rescue">救援指挥员</option>
                  </select>
              </div>

              <button 
                type="submit" 
                :disabled="isLoading"
                class="w-full bg-emerald-600 hover:bg-emerald-500 text-white font-bold py-3 rounded-lg shadow-lg transform transition-transform active:scale-95 disabled:opacity-50 disabled:cursor-not-allowed flex items-center justify-center"
              >
                  <span v-if="isLoading" class="animate-spin mr-2 h-5 w-5 border-2 border-white border-t-transparent rounded-full"></span>
                  {{ isLoading ? '正在认证...' : '登录系统' }}
              </button>
          </form>
          
          <div class="mt-6 text-center flex flex-col items-center gap-2">
              <router-link to="/register" class="text-emerald-400 hover:text-emerald-300 text-sm transition-colors">没有账户？立即注册</router-link>
              <span class="text-[10px] text-gray-500 uppercase tracking-widest opacity-50">安全连接 • v2.4.0</span>
          </div>
      </div>
  </div>
</template>
